<?php

namespace Database\Seeders;

use App\Models\Parameter;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParameterSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $userId = 1;

        // TIPO DE PARAMETRO
        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'TIPO_PARAMETRO',
                'nombre' => 'Imagen',
                'nombreCorto' => 'I',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 2,
                'codigoParametro' => 'TIPO_PARAMETRO',
                'nombre' => 'Texto',
                'nombreCorto' => 'T',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 2,
                'codigoParametro' => 'TIPO_PARAMETRO',
                'nombre' => 'URL',
                'nombreCorto' => 'U',
                'orden' => 4,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 4,
                'tipo' => 2,
                'codigoParametro' => 'TIPO_PARAMETRO',
                'nombre' => 'Archivo',
                'nombreCorto' => 'A',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);

        // TIPO DE CATEGORIA
        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'CATEGORIA',
                'nombre' => 'Router',
                'nombreCorto' => 'router',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 2,
                'codigoParametro' => 'CATEGORIA',
                'nombre' => 'Decodificador',
                'nombreCorto' => 'Deco',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 2,
                'codigoParametro' => 'CATEGORIA',
                'nombre' => 'Altavoz',
                'nombreCorto' => 'altavoz',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);


        // METODO DE PAGO
        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'METODO_PAGO',
                'nombre' => 'Efectivo',
                'nombreCorto' => 'Efectivo',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 2,
                'codigoParametro' => 'METODO_PAGO',
                'nombre' => 'Yape',
                'nombreCorto' => 'Yape',
                'orden' => 4,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 2,
                'codigoParametro' => 'METODO_PAGO',
                'nombre' => 'Plin',
                'nombreCorto' => 'Plin',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 4,
                'tipo' => 2,
                'codigoParametro' => 'METODO_PAGO',
                'nombre' => 'Transferencia Bancaria',
                'nombreCorto' => 'Transferencia',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);



        // ESTADO DE VENTA

        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_VENTA',
                'nombre' => 'Pendiente',
                'nombreCorto' => 'Pendiente',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_VENTA',
                'nombre' => 'Pagada',
                'nombreCorto' => 'Pagada',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_VENTA',
                'nombre' => 'Cancelada',
                'nombreCorto' => 'Cancelada',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);

        // ESTADO DE COMPRA

        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_COMPRA',
                'nombre' => 'Pendiente',
                'nombreCorto' => 'Pendiente',
                'orden' => 4,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_COMPRA',
                'nombre' => 'Pagada',
                'nombreCorto' => 'Pagada',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_COMPRA',
                'nombre' => 'Completada',
                'nombreCorto' => 'Completada',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 4,
                'tipo' => 2,
                'codigoParametro' => 'ESTADO_COMPRA',
                'nombre' => 'Cancelada',
                'nombreCorto' => 'Cancelada',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);


        // MOTIVOS DE PÉRDIDA DE COMPRA

        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 3,
                'codigoParametro' => 'MOTIVO_PERDIDA_COMPRA',
                'nombre' => 'Producto defectuoso',
                'nombreCorto' => 'Defectuoso',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 2,
                'tipo' => 3,
                'codigoParametro' => 'MOTIVO_PERDIDA_COMPRA',
                'nombre' => 'Producto robado',
                'nombreCorto' => 'Robo',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 3,
                'tipo' => 3,
                'codigoParametro' => 'MOTIVO_PERDIDA_COMPRA',
                'nombre' => 'Producto vencido',
                'nombreCorto' => 'Vencido',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
            [
                'idParametroPadre' => null,
                'idParametro' => 4,
                'tipo' => 3,
                'codigoParametro' => 'MOTIVO_PERDIDA_COMPRA',
                'nombre' => 'Otro motivo',
                'nombreCorto' => 'Otro',
                'orden' => 4,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);


        // TIPOS DE PÉRDIDA DE COMPRA
        Parameter::insert([
            [
                'idParametro' => 1,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_PERDIDA_COMPRA',
                'nombre' => 'Devolución',
                'nombreCorto' => 'Devolución',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 2,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_PERDIDA_COMPRA',
                'nombre' => 'Pérdida',
                'nombreCorto' => 'Pérdida',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 3,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_PERDIDA_COMPRA',
                'nombre' => 'Reembolso sin devolución',
                'nombreCorto' => 'Solo reembolso',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
        ]);




        // PARAMETROS PARA CATALOGO
        Parameter::insert([
            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 1,
                'codigoParametro' => 'CATALOGO_ENCABEZADO',
                'nombre' => 'imagen.png',
                'nombreCorto' => 'img',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 1,
                'codigoParametro' => 'CATALOGO_PORTADA',
                'nombre' => 'imagen.png',
                'nombreCorto' => 'img',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'EMPRESA_NOMBRE',
                'nombre' => 'Empresa ABC S.A.C.',
                'nombreCorto' => 'nombre',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'EMPRESA_NUMERO_TELEFONO',
                'nombre' => '+51 999999999',
                'nombreCorto' => '999999999',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'EMPRESA_PAGINA_WEB_',
                'nombre' => 'www.abc.com',
                'nombreCorto' => 'web',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'EMPRESA_DIRECCION',
                'nombre' => 'AV. Prueba Nª 144',
                'nombreCorto' => 'Av',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],


            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 2,
                'codigoParametro' => 'EMPRESA_CORREO',
                'nombre' => 'abc@empresa.com',
                'nombreCorto' => 'correo',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],

            [
                'idParametroPadre' => null,
                'idParametro' => 1,
                'tipo' => 4,
                'codigoParametro' => 'PLANTILLA_PRODUCTO',
                'nombre' => 'Plantilla importar producto',
                'nombreCorto' => 'plantilla',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
                'auditoriaFechaModificacion' => null,
                'auditoriaModificadoPor' => null,
                'auditoriaFechaEliminacion' => null,
                'auditoriaEliminadoPor' => null,
            ],
        ]);















        /***************************/

        // TIPOS DE HABITACIONES
        Parameter::insert([
            [
                'idParametro' => 1,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_HABITACION',
                'nombre' => 'Doble',
                'nombreCorto' => 'Doble',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 2,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_HABITACION',
                'nombre' => 'Individual',
                'nombreCorto' => 'Individual',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 3,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'TIPO_HABITACION',
                'nombre' => 'Matrimonial',
                'nombreCorto' => 'Matrimonial',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
        ]);


        // TIPOS DE HABITACIONES
        Parameter::insert([
            [
                'idParametro' => 1,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'PISO_HABITACION',
                'nombre' => 'Primero',
                'nombreCorto' => '1º',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 2,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'PISO_HABITACION',
                'nombre' => 'Segundo',
                'nombreCorto' => '2º',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 3,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'PISO_HABITACION',
                'nombre' => 'Tercero',
                'nombreCorto' => '3º',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
        ]);

        // ESTADOS DE HABITACION
        Parameter::insert([
            [
                'idParametro' => 2,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Check-out pendiente',
                'nombreCorto' => 'Check-out pendiente',
                'orden' => 1,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 1,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Disponible',
                'nombreCorto' => 'Disponible',
                'orden' => 2,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 3,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Inhabilitada',
                'nombreCorto' => 'Inhabilitada',
                'orden' => 3,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 4,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Limpieza',
                'nombreCorto' => 'Limpieza',
                'orden' => 4,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 5,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Mantenimiento',
                'nombreCorto' => 'Mantenimiento',
                'orden' => 5,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 6,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Ocupada',
                'nombreCorto' => 'Ocupada',
                'orden' => 6,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
            [
                'idParametro' => 7,
                'idParametroPadre' => null,
                'tipo' => 3,
                'codigoParametro' => 'ESTADO_HABITACION',
                'nombre' => 'Reservada',
                'nombreCorto' => 'Reservada',
                'orden' => 7,
                'auditoriaFechaCreacion' => $now,
                'auditoriaCreadoPor' => $userId,
            ],
        ]);
    }
}
